// Generated by CoffeeScript 1.3.1
var bob, view_model;

bob = new Backbone.Model({
  name: 'Bob',
  friend: new Backbone.Model({
    name: 'Fred'
  })
});

view_model = kb.viewModel(bob);

ko.applyBindings(view_model, $('#kbvm_bb_model')[0]);
