// Generated by CoffeeScript 1.3.3
var ViewModel, model, view_model;

model = new Backbone.Model({
  first_name: "Planet",
  last_name: "Earth"
});

ViewModel = function(model) {
  this.first_name = kb.observable(model, 'first_name');
  this.last_name = kb.observable(model, 'first_name');
  this.full_name = ko.computed((function() {
    return "" + (this.first_name()) + " " + (this.last_name());
  }), this);
  return this;
};

view_model = new ViewModel(model);

ko.applyBindings(view_model, $('#kb_observable')[0]);
