// Generated by CoffeeScript 1.3.3
var ViewModel, model, view_model;

model = {
  first_name: "Planet",
  last_name: "Earth"
};

ViewModel = function(model) {
  this.first_name = ko.observable(model.first_name);
  this.last_name = ko.observable(model.last_name);
  this.full_name = ko.computed((function() {
    return "" + (this.first_name()) + " " + (this.last_name());
  }), this);
  return this;
};

view_model = new ViewModel(model);

ko.applyBindings(view_model, $('#ko_basic')[0]);
