// Generated by CoffeeScript 1.3.3

/*
  knockback.js 0.16.0beta1
  (c) 2011, 2012 Kevin Malakoff.
  Knockback.js is freely distributable under the MIT license.
  See the following for full license details:
    https://github.com/kmalakoff/knockback/blob/master/LICENSE
  Dependencies: Knockout.js, Backbone.js, and Underscore.js.
    Optional dependency: Backbone.ModelRef.js.
*/


(function() {
  var Backbone, Knockback, kb, ko, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  if (typeof require !== 'undefined') {
    try {
      _ = require('lodash');
    } catch (e) {
      _ = require('underscore');
    }
  } else {
    _ = this._;
  }

  if (_ && (_.hasOwnProperty('_'))) {
    _ = _._;
  }

  Backbone = !this.Backbone && (typeof require !== 'undefined') ? require('backbone') : this.Backbone;

  ko = !this.ko && (typeof require !== 'undefined') ? require('knockout') : this.ko;

  Knockback = kb = this.Knockback = this.kb = typeof exports !== 'undefined' ? exports : {};

  kb.VERSION = '0.16.0beta1';

  kb.locale_manager = void 0;

  kb.TYPE_UNKNOWN = 0;

  kb.TYPE_SIMPLE = 1;

  kb.TYPE_MODEL = 2;

  kb.TYPE_COLLECTION = 3;

  /*
    knockback_statistics.js
    (c) 2012 Kevin Malakoff.
    Knockback.Stats is freely distributable under the MIT license.
    See the following for full license details:
      https://github.com/kmalakoff/knockback/blob/master/LICENSE
  */


  kb.Statistics = (function() {

    function Statistics() {
      this.type_trackers = {};
    }

    Statistics.prototype.typeTracker = function(type) {
      var type_tracker;
      if (this.type_trackers.hasOwnProperty(type)) {
        return this.type_trackers[type];
      }
      type_tracker = [];
      this.type_trackers[type] = type_tracker;
      return type_tracker;
    };

    Statistics.prototype.register = function(type, obj) {
      return this.typeTracker(type).push(obj);
    };

    Statistics.prototype.unregister = function(type, obj) {
      var index, type_tracker;
      type_tracker = this.typeTracker(type);
      index = _.indexOf(type_tracker, obj);
      if (index < 0) {
        throw "failed to unregister type: " + type;
      }
      return type_tracker.splice(index, 1);
    };

    Statistics.prototype.registeredCount = function(type) {
      return this.typeTracker(type).length;
    };

    return Statistics;

  })();

  /*
    knockback_utils.js
    (c) 2011, 2012 Kevin Malakoff.
    Knockback.js is freely distributable under the MIT license.
    See the following for full license details:
      https://github.com/kmalakoff/knockback/blob/master/LICENSE
    Dependencies: Knockout.js, Backbone.js, and Underscore.js.
      Optional dependency: Backbone.ModelRef.js.
  */


  kb.utils = {};

  kb.utils.legacyWarning = function(identifier, last_version, message) {
    var _base;
    kb._legacy_warnings || (kb._legacy_warnings = {});
    (_base = kb._legacy_warnings)[identifier] || (_base[identifier] = 0);
    kb._legacy_warnings[identifier]++;
    return console.warn("warning: '" + identifier + "' has been deprecated (will be removed in Knockback after " + last_version + "). " + message + ".");
  };

  kb.utils.wrappedDestroy = function(owner) {
    var __kb;
    if (!owner.__kb) {
      return;
    }
    __kb = owner.__kb;
    owner.__kb = null;
    if (__kb.model_ref) {
      kb.utils.wrappedModelRef(owner, null);
    }
    if (__kb.value_observable && !__kb.store) {
      kb.utils.release(__kb.value_observable);
    }
    if (__kb.observable) {
      kb.utils.wrappedDestroy(__kb.observable);
      if (__kb.observable.dispose) {
        __kb.observable.dispose();
      }
    }
    if (__kb.store_is_owned) {
      return __kb.store.destroy();
    }
  };

  kb.utils.wrappedByKey = function(owner, key, value) {
    if (arguments.length === 2) {
      if (owner && owner.__kb && owner.__kb.hasOwnProperty(key)) {
        return owner.__kb[key];
      } else {
        return void 0;
      }
    }
    if (!owner) {
      throw "Knockback: no owner for wrapping " + key;
    }
    owner.__kb || (owner.__kb = {});
    owner.__kb[key] = value;
    return value;
  };

  kb.utils.wrappedObservable = function(instance, observable) {
    if (arguments.length === 1) {
      return kb.utils.wrappedByKey(instance, 'observable');
    }
    kb.utils.wrappedByKey(instance, 'observable', observable);
    if (observable) {
      kb.utils.wrappedByKey(observable, 'instance', instance);
    }
    return observable;
  };

  kb.utils.wrappedModel = function(observable, value) {
    var obj;
    if (arguments.length === 1) {
      obj = kb.utils.wrappedByKey(observable, 'obj');
      if (_.isUndefined(obj)) {
        return observable;
      } else {
        return obj;
      }
    } else {
      return kb.utils.wrappedByKey(observable, 'obj', value);
    }
  };

  kb.utils.wrappedModelRef = function(observable, value, options) {
    var previous_options, previous_value;
    previous_value = kb.utils.wrappedByKey(observable, 'model_ref');
    if (arguments.length === 1) {
      return previous_value;
    }
    if (value === previous_value) {
      return value;
    }
    if (value) {
      value.retain();
    }
    if (previous_value) {
      previous_options = kb.utils.wrappedByKey(observable, 'model_ref_options');
      previous_value.unbind('loaded', previous_options.loaded)(previous_options.loaded);
      previous_value.unbind('unloaded', previous_options.unloaded)(previous_options.unloaded);
      previous_value.release();
    }
    kb.utils.wrappedByKey(observable, 'model_ref', value);
    if (value) {
      options = kb.utils.wrappedByKey(observable, 'model_ref_options', options ? options : {});
      if (options.loaded) {
        value.bind('loaded', options.loaded);
      }
      if (options.unloaded) {
        value.bind('unloaded', options.unloaded);
      }
    }
    return value;
  };

  kb.utils.wrappedObject = function(observable, value) {
    if (arguments.length === 1) {
      return kb.utils.wrappedByKey(observable, 'obj');
    } else {
      return kb.utils.wrappedByKey(observable, 'obj', value);
    }
  };

  kb.utils.wrappedStore = function(observable, value) {
    if (arguments.length === 1) {
      return kb.utils.wrappedByKey(observable, 'store');
    } else {
      return kb.utils.wrappedByKey(observable, 'store', value);
    }
  };

  kb.utils.wrappedStoreIsOwned = function(observable, value) {
    if (arguments.length === 1) {
      return kb.utils.wrappedByKey(observable, 'store_is_owned');
    } else {
      return kb.utils.wrappedByKey(observable, 'store_is_owned', value);
    }
  };

  kb.utils.wrappedFactory = function(observable, value) {
    if (arguments.length === 1) {
      return kb.utils.wrappedByKey(observable, 'factory');
    } else {
      return kb.utils.wrappedByKey(observable, 'factory', value);
    }
  };

  kb.utils.wrappedPath = function(observable, value) {
    if (arguments.length === 1) {
      return kb.utils.wrappedByKey(observable, 'path');
    } else {
      return kb.utils.wrappedByKey(observable, 'path', value);
    }
  };

  kb.utils.setToDefault = function(obj) {
    var key, observable, _results;
    if (!obj) {
      return;
    }
    if (ko.isObservable(obj)) {
      return typeof obj.setToDefault === "function" ? obj.setToDefault() : void 0;
    } else if (_.isObject(obj)) {
      _results = [];
      for (key in obj) {
        observable = obj[key];
        _results.push(observable && (key !== '__kb') ? kb.utils.setToDefault(observable) : void 0);
      }
      return _results;
    }
  };

  kb.utils.release = function(obj, keys_only) {
    var key, value;
    if (!obj) {
      return false;
    }
    if (!keys_only && (ko.isObservable(obj) || (obj instanceof kb.Observables) || (typeof obj.release === 'function') || (typeof obj.destroy === 'function'))) {
      if (obj.release) {
        obj.release();
      } else if (obj.destroy) {
        obj.destroy();
      } else if (obj.dispose) {
        obj.dispose();
      }
      return true;
    } else if (_.isObject(obj) && !(typeof obj === 'function')) {
      for (key in obj) {
        value = obj[key];
        if (!value || (key === '__kb') || ((typeof value === 'function') && !ko.isObservable(value))) {
          continue;
        }
        if (kb.utils.release(value)) {
          obj[key] = null;
        }
      }
      return true;
    }
    return false;
  };

  kb.utils.valueType = function(observable) {
    var instance;
    if (!observable) {
      return kb.TYPE_UNKNOWN;
    }
    if (observable instanceof kb.ViewModel) {
      return kb.TYPE_MODEL;
    }
    if (!(observable.__kb && observable.__kb.instance)) {
      return kb.TYPE_SIMPLE;
    }
    instance = observable.__kb.instance;
    if (instance instanceof kb.AttributeObservable) {
      return observable.valueType();
    }
    if (instance instanceof kb.CollectionObservable) {
      return kb.TYPE_COLLECTION;
    }
    return kb.TYPE_SIMPLE;
  };

  kb.utils.observableInstanceOf = function(observable, type) {
    if (!observable) {
      return false;
    }
    if (!(observable.__kb && observable.__kb.instance)) {
      return false;
    }
    return observable.__kb.instance instanceof type;
  };

  kb.utils.pathJoin = function(path1, path2) {
    var path;
    if (!path1) {
      path = '';
    } else {
      path = path1[path1.length - 1] !== '.' ? "" + path1 + "." : path1;
    }
    path += path2;
    return path;
  };

  kb.utils.optionsPathJoin = function(options, path) {
    return _.defaults({
      path: kb.utils.pathJoin(options.path, path)
    }, options);
  };

  /*
    knockback_ref_countable.js
    (c) 2012 Kevin Malakoff.
    Knockback.RefCountable is freely distributable under the MIT license.
    See the following for full license details:
      https://github.com/kmalakoff/knockback/blob/master/LICENSE
  */


  kb.RefCountable = (function() {

    RefCountable.extend = Backbone.Model.extend;

    function RefCountable() {
      this.__kb_ref_count = 1;
    }

    RefCountable.prototype.__destroy = function() {};

    RefCountable.prototype.retain = function() {
      if (this.__kb_ref_count <= 0) {
        throw "RefCountable: ref_count is corrupt: " + this.__kb_ref_count;
      }
      this.__kb_ref_count++;
      return this;
    };

    RefCountable.prototype.release = function(all) {
      if (this.__kb_ref_count <= 0) {
        throw "RefCountable: ref_count is corrupt: " + this.__kb_ref_count;
      }
      if (all) {
        this.__kb_ref_count = 0;
      } else {
        this.__kb_ref_count--;
      }
      if (!this.__kb_ref_count) {
        this.__destroy();
      }
      return this;
    };

    RefCountable.prototype.refCount = function() {
      return this.__kb_ref_count;
    };

    return RefCountable;

  })();

  /*
    knockback_factory.js
    (c) 2011, 2012 Kevin Malakoff.
    Knockback.Factory is freely distributable under the MIT license.
    See the following for full license details:
      https://github.com/kmalakoff/knockback/blob/master/LICENSE
  */


  kb.Factory = (function() {

    function Factory(parent_factory) {
      this.parent_factory = parent_factory;
      this.paths = {};
    }

    Factory.prototype.hasPath = function(path) {
      return this.paths.hasOwnProperty(path) || (this.parent_factory && this.parent_factory.hasPath(path));
    };

    Factory.prototype.addPathMapping = function(path, create_info) {
      return this.paths[path] = create_info;
    };

    Factory.prototype.addPathMappings = function(mappings) {
      var create_info, path, _results;
      _results = [];
      for (path in mappings) {
        create_info = mappings[path];
        _results.push(this.paths[path] = create_info);
      }
      return _results;
    };

    Factory.prototype.creatorForPath = function(obj, path) {
      var creator;
      creator = this.paths[path];
      if (creator) {
        if (creator.view_model) {
          return creator.view_model;
        } else {
          return creator;
        }
      }
      if (this.parent_factory) {
        creator = this.parent_factory.creatorForPath(obj, path);
        if (creator) {
          return creator;
        }
      }
      if (obj instanceof Backbone.Model) {
        return kb.ViewModel;
      }
      if (obj instanceof Backbone.Collection) {
        return kb.CollectionObservable;
      }
      return null;
    };

    Factory.prototype.createForPath = function(obj, path, store, creator) {
      if (!creator) {
        creator = this.creatorForPath(obj, path);
      }
      if (!creator) {
        return ko.observable(obj);
      }
      if (creator.hasOwnProperty('models_only')) {
        return obj(creator.models_only);
        return kb.Factory.createDefault(obj, {
          store: store,
          factory: this,
          path: path
        });
      }
      if (typeof creator === 'function') {
        return new creator(obj, {
          store: store,
          factory: this,
          path: path,
          creator: creator
        });
      }
      if (creator.create) {
        return creator.create(obj, {
          store: store,
          factory: this,
          path: path,
          creator: creator
        });
      }
      throw "unrecognized creator for " + path;
    };

    Factory.createDefault = function(obj, options) {
      if (obj instanceof Backbone.Model) {
        return kb.viewModel(obj, options);
      }
      if (obj instanceof Backbone.Collection) {
        return kb.collectionObservable(obj, options);
      }
      return ko.observable(obj);
    };

    return Factory;

  })();

  /*
    knockback_store.js
    (c) 2012 Kevin Malakoff.
    Knockback.Store is freely distributable under the MIT license.
    See the following for full license details:
      https://github.com/kmalakoff/knockback/blob/master/LICENSE
  */


  kb.Store = (function() {

    Store.registerOrCreateStoreFromOptions = function(obj, observable, options) {
      if (options.store) {
        kb.utils.wrappedStore(observable, options.store);
        return options.store.registerObservable(obj, observable, options);
      } else {
        kb.utils.wrappedStore(observable, new kb.Store());
        return kb.utils.wrappedStoreIsOwned(observable, true);
      }
    };

    function Store() {
      this.objects = [];
      this.observables = [];
    }

    Store.prototype.destroy = function() {
      var index, observable, _ref, _ref1;
      this.objects = null;
      _ref = this.observables;
      for (index in _ref) {
        observable = _ref[index];
        if (!kb.utils.observableInstanceOf(observable, kb.CollectionObservable)) {
          continue;
        }
        this.observables[index] = null;
        observable.release(true);
      }
      _ref1 = this.observables;
      for (index in _ref1) {
        observable = _ref1[index];
        if (!observable) {
          continue;
        }
        this.observables[index] = null;
        if (observable && observable.release) {
          observable.release(true);
        } else {
          kb.utils.release(observable);
        }
      }
      return this.observables = null;
    };

    Store.prototype.registerObservable = function(obj, observable, options) {
      if (options == null) {
        options = {};
      }
      if (!obj) {
        return;
      }
      this.objects.push(obj);
      kb.utils.wrappedObject(observable, obj);
      this.observables.push(observable);
      if (typeof observable.retain === "function") {
        observable.retain();
      }
      if (options.creator) {
        return observable.__kb.creator = options.creator;
      } else if (options.path && options.factory) {
        return observable.__kb.creator = options.factory.creatorForPath(obj, options.path);
      }
    };

    Store.prototype.findOrCreateObservable = function(obj, path, factory) {
      var creator, index, observable, test, _i, _len, _ref;
      creator = factory.creatorForPath(obj, path);
      if (!creator) {
        return ko.observable(obj);
      }
      if (creator.models_only) {
        return obj;
      }
      if (!(obj instanceof Backbone.Collection)) {
        _ref = this.objects;
        for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
          test = _ref[index];
          observable = this.observables[index];
          if ((test === obj) && (observable.__kb.creator === creator)) {
            if (typeof observable.retain === "function") {
              observable.retain();
            }
            return observable;
          }
        }
      }
      observable = factory.createForPath(obj, path, this, creator);
      if (!observable) {
        throw "Factory counldn't create observable for " + path;
      }
      index = _.indexOf(this.observables, observable);
      if (index < 0) {
        this.registerObservable(obj, observable, {
          creator: creator
        });
      }
      return observable;
    };

    Store.prototype.releaseObservable = function(observable, owns_store) {
      var index;
      if (!observable) {
        return;
      }
      index = _.indexOf(this.observables, observable);
      if (!(index >= 0)) {
        return;
      }
      if (arguments.length === 2 && !owns_store && !observable.release) {
        return;
      }
      kb.utils.release(observable);
      if (observable.refCount && observable.refCount() > 0) {
        return;
      }
      kb.utils.wrappedObject(observable, null);
      if (this.observables[index] !== observable) {
        index = _.indexOf(this.observables, observable);
      }
      this.objects[index] = null;
      return this.observables[index] = null;
    };

    return Store;

  })();

  /*
    knockback_collection_observable.js
    (c) 2011, 2012 Kevin Malakoff.
    Knockback.CollectionObservable is freely distributable under the MIT license.
    See the following for full license details:
      https://github.com/kmalakoff/knockback/blob/master/LICENSE
  */


  kb.CollectionObservable = (function(_super) {

    __extends(CollectionObservable, _super);

    function CollectionObservable(collection, options) {
      var factory, observable;
      if (options == null) {
        options = {};
      }
      if (!collection) {
        throw 'CollectionObservable: collection is missing';
      }
      CollectionObservable.__super__.constructor.apply(this, arguments);
      if (kb.statistics) {
        kb.statistics.register('kb.CollectionObservable', this);
      }
      observable = kb.utils.wrappedObservable(this, ko.observableArray([]));
      this.in_edit = 0;
      this.__kb || (this.__kb = {});
      this.__kb._onCollectionReset = _.bind(this._onCollectionReset, this);
      this.__kb._onCollectionResort = _.bind(this._onCollectionResort, this);
      this.__kb._onModelAdd = _.bind(this._onModelAdd, this);
      this.__kb._onModelRemove = _.bind(this._onModelRemove, this);
      this.__kb._onModelChange = _.bind(this._onModelChange, this);
      kb.Store.registerOrCreateStoreFromOptions(collection, observable, options);
      factory = kb.utils.wrappedFactory(observable, new kb.Factory(options.factory));
      if (options.mappings) {
        factory.addPathMappings(options.mappings);
      }
      kb.utils.wrappedPath(observable, options.path);
      this.models_path = kb.utils.pathJoin(options.path, 'models');
      if (!factory.hasPath(this.models_path)) {
        if (options.hasOwnProperty('models_only')) {
          if (options.models_only) {
            factory.addPathMapping(this.models_path, {
              models_only: options.models_only
            });
            this.models_only = options.models_only;
          } else {
            factory.addPathMapping(this.models_path, kb.ViewModel);
          }
        } else if (options.view_model) {
          factory.addPathMapping(this.models_path, options.view_model);
        } else if (options.create) {
          factory.addPathMapping(this.models_path, {
            create: options.create
          });
        } else {
          factory.addPathMapping(this.models_path, kb.ViewModel);
        }
      }
      this.sort_attribute = options.sort_attribute;
      this.sorted_index = options.sorted_index;
      observable.retain = _.bind(this.retain, this);
      observable.refCount = _.bind(this.refCount, this);
      observable.release = _.bind(this.release, this);
      observable.collection = _.bind(this.collection, this);
      observable.viewModelByModel = _.bind(this.viewModelByModel, this);
      observable.sortedIndex = _.bind(this.sortedIndex, this);
      observable.sortAttribute = _.bind(this.sortAttribute, this);
      observable.hasViewModels = _.bind(this.hasViewModels, this);
      observable.bind = _.bind(this.bind, this);
      observable.unbind = _.bind(this.unbind, this);
      observable.trigger = _.bind(this.trigger, this);
      kb.utils.wrappedObject(observable, null);
      this.collection(collection, {
        silent: true,
        'defer': options['defer']
      });
      observable.subscribe(_.bind(this._onObservableArrayChange, this));
      return observable;
    }

    CollectionObservable.prototype.__destroy = function() {
      this.collection(null);
      kb.utils.wrappedDestroy(this);
      CollectionObservable.__super__.__destroy.apply(this, arguments);
      if (kb.statistics) {
        return kb.statistics.unregister('kb.CollectionObservable', this);
      }
    };

    CollectionObservable.prototype.retain = function() {
      CollectionObservable.__super__.retain.apply(this, arguments);
      return kb.utils.wrappedObservable(this);
    };

    CollectionObservable.prototype.release = function() {
      var observable;
      observable = kb.utils.wrappedObservable(this);
      CollectionObservable.__super__.release.apply(this, arguments);
      return observable;
    };

    CollectionObservable.prototype.collection = function(collection, options) {
      var observable, previous_collection;
      observable = kb.utils.wrappedObservable(this);
      previous_collection = kb.utils.wrappedObject(observable);
      if (arguments.length === 0) {
        observable();
        return previous_collection;
      }
      if (collection === previous_collection) {
        return;
      }
      if (previous_collection) {
        this._clear();
        this._collectionUnbind(previous_collection);
        if (typeof previous_collection.release === "function") {
          previous_collection.release();
        }
      }
      kb.utils.wrappedObject(observable, collection);
      if (collection) {
        if (typeof collection.retain === "function") {
          collection.retain();
        }
        this._collectionBind(collection);
        this.sortedIndex(this.sorted_index, this.sort_attribute, options);
      }
      return collection;
    };

    CollectionObservable.prototype.sortedIndex = function(sorted_index, sort_attribute, options) {
      var _resync,
        _this = this;
      if (options == null) {
        options = {};
      }
      if (sorted_index) {
        this.sorted_index = sorted_index;
        this.sort_attribute = sort_attribute;
      } else if (sort_attribute) {
        this.sort_attribute = sort_attribute;
        this.sorted_index = this._sortAttributeFn(sort_attribute);
      } else {
        this.sort_attribute = null;
        this.sorted_index = null;
      }
      _resync = function() {
        var collection, observable;
        observable = kb.utils.wrappedObservable(_this);
        collection = kb.utils.wrappedObject(observable);
        if ((collection.models.length === 0) && (observable().length === 0)) {
          return;
        }
        _this._collectionResync(true);
        if (!options.silent) {
          return _this.trigger('resort', observable());
        }
      };
      if (options['defer']) {
        _.defer(_resync);
      } else {
        _resync();
      }
      return this;
    };

    CollectionObservable.prototype.sortAttribute = function(sort_attribute, sorted_index, silent) {
      return this.sortedIndex(sorted_index, sort_attribute, silent);
    };

    CollectionObservable.prototype.viewModelByModel = function(model) {
      var id_attribute, observable;
      if (!this.hasViewModels()) {
        return null;
      }
      observable = kb.utils.wrappedObservable(this);
      id_attribute = model.hasOwnProperty(model.idAttribute) ? model.idAttribute : 'cid';
      return _.find(observable(), function(test) {
        return test.__kb.obj[id_attribute] === model[id_attribute];
      });
    };

    CollectionObservable.prototype.hasViewModels = function() {
      return !this.models_only;
    };

    CollectionObservable.prototype._collectionBind = function(collection) {
      var event, _i, _j, _len, _len1, _ref, _ref1;
      if (!collection) {
        return;
      }
      collection.bind('reset', this.__kb._onCollectionReset);
      if (!this.sorted_index) {
        collection.bind('resort', this.__kb._onCollectionResort);
      }
      _ref = ['new', 'add'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        event = _ref[_i];
        collection.bind(event, this.__kb._onModelAdd);
      }
      _ref1 = ['remove', 'destroy'];
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        event = _ref1[_j];
        collection.bind(event, this.__kb._onModelRemove);
      }
      return collection.bind('change', this.__kb._onModelChange);
    };

    CollectionObservable.prototype._collectionUnbind = function(collection) {
      var event, _i, _j, _len, _len1, _ref, _ref1;
      if (!collection) {
        return;
      }
      collection.unbind('reset', this.__kb._onCollectionReset);
      if (!this.sorted_index) {
        collection.unbind('resort', this.__kb._onCollectionResort);
      }
      _ref = ['new', 'add'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        event = _ref[_i];
        collection.unbind(event, this.__kb._onModelAdd);
      }
      _ref1 = ['remove', 'destroy'];
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        event = _ref1[_j];
        collection.unbind(event, this.__kb._onModelRemove);
      }
      return collection.unbind('change', this.__kb._onModelChange);
    };

    CollectionObservable.prototype._onCollectionReset = function() {
      if (this.in_edit) {
        return;
      }
      return this._collectionResync();
    };

    CollectionObservable.prototype._onCollectionResort = function(model_or_models) {
      var observable;
      if (this.sorted_index) {
        throw 'CollectionObservable: collection sorted_index unexpected';
      }
      if (_.isArray(model_or_models)) {
        observable = kb.utils.wrappedObservable(this);
        return this.trigger('resort', observable());
      } else {
        return this._onModelResort(model_or_models);
      }
    };

    CollectionObservable.prototype._onModelAdd = function(model) {
      var add_index, collection, model_observable, observable;
      model_observable = this._createModelObervable(model);
      observable = kb.utils.wrappedObservable(this);
      collection = kb.utils.wrappedObject(observable);
      if (this.sorted_index) {
        add_index = this.sorted_index(observable(), model_observable);
      } else {
        add_index = collection.indexOf(model);
      }
      this.in_edit++;
      observable.splice(add_index, 0, model_observable);
      this.in_edit--;
      return this.trigger('add', model_observable, observable());
    };

    CollectionObservable.prototype._onModelRemove = function(model) {
      var model_observable, observable;
      model_observable = this.hasViewModels() ? this.viewModelByModel(model) : model;
      if (!model_observable) {
        return;
      }
      observable = kb.utils.wrappedObservable(this);
      this.in_edit++;
      observable.remove(model_observable);
      this.in_edit--;
      this.trigger('remove', model_observable, observable);
      if (this.hasViewModels()) {
        return kb.utils.wrappedStore(observable).releaseObservable(model_observable, kb.utils.wrappedStoreIsOwned(observable));
      }
    };

    CollectionObservable.prototype._onModelChange = function(model) {
      if (this.sorted_index && (!this.sort_attribute || model.hasChanged(this.sort_attribute))) {
        return this._onModelResort(model);
      }
    };

    CollectionObservable.prototype._onModelResort = function(model) {
      var collection, model_observable, new_index, observable, previous_index, sorted_model_observables;
      observable = kb.utils.wrappedObservable(this);
      collection = kb.utils.wrappedObject(observable);
      model_observable = this.hasViewModels() ? this.viewModelByModel(model) : model;
      previous_index = observable.indexOf(model_observable);
      if (this.sorted_index) {
        sorted_model_observables = _.clone(observable());
        sorted_model_observables.splice(previous_index, 1);
        new_index = this.sorted_index(sorted_model_observables, model_observable);
      } else {
        new_index = collection.indexOf(model);
      }
      if (previous_index === new_index) {
        return;
      }
      this.in_edit++;
      observable.splice(previous_index, 1);
      observable.splice(new_index, 0, model_observable);
      this.in_edit--;
      return this.trigger('resort', model_observable, observable(), new_index);
    };

    CollectionObservable.prototype._onObservableArrayChange = function(values) {
      var collection, observable;
      if (this.in_edit) {
        return;
      }
      observable = kb.utils.wrappedObservable(this);
      collection = kb.utils.wrappedObject(observable);
      this.in_edit++;
      collection.reset(_.map(values, function(test) {
        return kb.utils.wrappedModel(test);
      }));
      return this.in_edit--;
    };

    CollectionObservable.prototype._clear = function(silent) {
      var model_observable, model_observables, observable, store, _i, _len, _results;
      observable = kb.utils.wrappedObservable(this);
      if (!silent) {
        this.trigger('remove', observable());
      }
      this.in_edit++;
      model_observables = observable.removeAll();
      this.in_edit--;
      store = kb.utils.wrappedStore(observable);
      if (this.hasViewModels()) {
        _results = [];
        for (_i = 0, _len = model_observables.length; _i < _len; _i++) {
          model_observable = model_observables[_i];
          _results.push(store.releaseObservable(model_observable, kb.utils.wrappedStoreIsOwned(observable)));
        }
        return _results;
      }
    };

    CollectionObservable.prototype._collectionResync = function(silent) {
      var add_index, collection, model, model_observable, model_observables, observable, _i, _len, _ref,
        _this = this;
      this._clear(silent);
      observable = kb.utils.wrappedObservable(this);
      collection = kb.utils.wrappedObject(observable);
      if (this.sorted_index) {
        model_observables = [];
        _ref = collection.models;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          model = _ref[_i];
          model_observable = this._createModelObervable(model);
          add_index = this.sorted_index(model_observables, model_observable);
          model_observables.splice(add_index, 0, model_observable);
        }
      } else {
        model_observables = this.hasViewModels() ? _.map(collection.models, function(model) {
          return _this._createModelObervable(model);
        }) : _.clone(collection.models);
      }
      this.in_edit++;
      observable(model_observables);
      this.in_edit--;
      if (!silent) {
        return this.trigger('add', observable());
      }
    };

    CollectionObservable.prototype._sortAttributeFn = function(sort_attribute) {
      if (this.hasViewModels()) {
        return function(view_models, model) {
          return _.sortedIndex(view_models, model, function(test) {
            return kb.utils.wrappedModel(test).get(sort_attribute);
          });
        };
      } else {
        return function(models, model) {
          return _.sortedIndex(models, model, function(test) {
            return test.get(sort_attribute);
          });
        };
      }
    };

    CollectionObservable.prototype._createModelObervable = function(model) {
      var observable;
      observable = kb.utils.wrappedObservable(this);
      if (this.hasViewModels()) {
        return kb.utils.wrappedStore(observable).findOrCreateObservable(model, this.models_path, kb.utils.wrappedFactory(observable));
      } else {
        return model;
      }
    };

    return CollectionObservable;

  })(kb.RefCountable);

  __extends(kb.CollectionObservable.prototype, Backbone.Events);

  kb.collectionObservable = function(collection, options) {
    return new kb.CollectionObservable(collection, options);
  };

  kb.sortedIndexWrapAttr = kb.siwa = function(attribute_name, wrapper_constructor) {
    return function(models, model) {
      return _.sortedIndex(models, model, function(test) {
        return new wrapper_constructor(kb.utils.wrappedModel(test).get(attribute_name));
      });
    };
  };

  /*
    knockback_default_wrapper.js
    (c) 2011, 2012 Kevin Malakoff.
    Knockback.DefaultWrapper is freely distributable under the MIT license.
    See the following for full license details:
      https://github.com/kmalakoff/knockback/blob/master/LICENSE
  */


  kb.DefaultWrapper = (function() {

    function DefaultWrapper(target_observable, default_value) {
      var observable,
        _this = this;
      this.default_value = default_value;
      observable = kb.utils.wrappedObservable(this, ko.dependentObservable({
        read: function() {
          var current_default, current_target;
          current_target = ko.utils.unwrapObservable(target_observable());
          current_default = ko.utils.unwrapObservable(_this.default_value);
          if (!current_target) {
            return current_default;
          } else {
            return current_target;
          }
        },
        write: function(value) {
          return target_observable(value);
        }
      }));
      observable.destroy = _.bind(this.destroy, this);
      observable.setToDefault = _.bind(this.setToDefault, this);
      return observable;
    }

    DefaultWrapper.prototype.destroy = function() {
      var _base;
      if (this.default_value) {
        if (typeof (_base = this.default_value).dispose === "function") {
          _base.dispose();
        }
        this.default_value = null;
      }
      return kb.utils.wrappedDestroy(this);
    };

    DefaultWrapper.prototype.setToDefault = function() {
      var observable;
      observable = kb.utils.wrappedObservable(this);
      return observable(this.default_value);
    };

    return DefaultWrapper;

  })();

  kb.defaultWrapper = function(target, default_value) {
    return new kb.DefaultWrapper(target, default_value);
  };

  /*
    knockback_formatted_observable.js
    (c) 2011, 2012 Kevin Malakoff.
    Knockback.FormattedObservable is freely distributable under the MIT license.
    See the following for full license details:
      https://github.com/kmalakoff/knockback/blob/master/LICENSE
  */


  kb.toFormattedString = function(format) {
    var arg, args, index, parameter_index, result, value;
    result = format.slice();
    args = Array.prototype.slice.call(arguments, 1);
    for (index in args) {
      arg = args[index];
      value = ko.utils.unwrapObservable(arg);
      if (!value) {
        value = '';
      }
      parameter_index = format.indexOf("\{" + index + "\}");
      while (parameter_index >= 0) {
        result = result.replace("{" + index + "}", value);
        parameter_index = format.indexOf("\{" + index + "\}", parameter_index + 1);
      }
    }
    return result;
  };

  kb.parseFormattedString = function(string, format) {
    var count, format_indices_to_matched_indices, index, match_index, matches, parameter_count, parameter_index, positions, regex, regex_string, results, sorted_positions, _i, _results;
    regex_string = format.slice();
    index = 0;
    parameter_count = 0;
    positions = {};
    while (regex_string.search("\\{" + index + "\\}") >= 0) {
      parameter_index = format.indexOf("\{" + index + "\}");
      while (parameter_index >= 0) {
        regex_string = regex_string.replace("\{" + index + "\}", '(.*)');
        positions[parameter_index] = index;
        parameter_count++;
        parameter_index = format.indexOf("\{" + index + "\}", parameter_index + 1);
      }
      index++;
    }
    count = index;
    regex = new RegExp(regex_string);
    matches = regex.exec(string);
    if (matches) {
      matches.shift();
    }
    if (!matches || (matches.length !== parameter_count)) {
      return _.map((function() {
        _results = [];
        for (var _i = 1; 1 <= count ? _i <= count : _i >= count; 1 <= count ? _i++ : _i--){ _results.push(_i); }
        return _results;
      }).apply(this), function() {
        return '';
      });
    }
    sorted_positions = _.sortBy(_.keys(positions), function(parameter_index, format_index) {
      return parseInt(parameter_index, 10);
    });
    format_indices_to_matched_indices = {};
    for (match_index in sorted_positions) {
      parameter_index = sorted_positions[match_index];
      index = positions[parameter_index];
      if (format_indices_to_matched_indices.hasOwnProperty(index)) {
        continue;
      }
      format_indices_to_matched_indices[index] = match_index;
    }
    results = [];
    index = 0;
    while (index < count) {
      results.push(matches[format_indices_to_matched_indices[index]]);
      index++;
    }
    return results;
  };

  kb.FormattedObservable = (function() {

    function FormattedObservable(format, args) {
      var observable, observable_args;
      if (_.isArray(args)) {
        format = format;
        observable_args = args;
      } else {
        observable_args = Array.prototype.slice.call(arguments, 1);
      }
      observable = kb.utils.wrappedObservable(this, ko.dependentObservable({
        read: function() {
          var arg, _i, _len;
          args = [ko.utils.unwrapObservable(format)];
          for (_i = 0, _len = observable_args.length; _i < _len; _i++) {
            arg = observable_args[_i];
            args.push(ko.utils.unwrapObservable(arg));
          }
          return kb.toFormattedString.apply(null, args);
        },
        write: function(value) {
          var index, matches, max_count, _results;
          matches = kb.parseFormattedString(value, ko.utils.unwrapObservable(format));
          max_count = Math.min(observable_args.length, matches.length);
          index = 0;
          _results = [];
          while (index < max_count) {
            observable_args[index](matches[index]);
            _results.push(index++);
          }
          return _results;
        }
      }));
      return observable;
    }

    FormattedObservable.prototype.destroy = function() {
      return kb.utils.wrappedDestroy(this);
    };

    return FormattedObservable;

  })();

  kb.formattedObservable = function(format, args) {
    return new kb.FormattedObservable(format, Array.prototype.slice.call(arguments, 1));
  };

  /*
    knockback_localized_observable.js
    (c) 2011, 2012 Kevin Malakoff.
    Knockback.LocalizedObservable is freely distributable under the MIT license.
    See the following for full license details:
      https://github.com/kmalakoff/knockback/blob/master/LICENSE
  */


  kb.LocalizedObservable = (function() {

    LocalizedObservable.extend = Backbone.Model.extend;

    function LocalizedObservable(value_holder, options, view_model) {
      var observable, value;
      this.value_holder = value_holder;
      if (options == null) {
        options = {};
      }
      this.view_model = view_model != null ? view_model : {};
      if (!this.read) {
        throw 'LocalizedObservable: options.read is missing';
      }
      if (!kb.locale_manager) {
        throw 'LocalizedObservable: kb.locale_manager is not defined';
      }
      this.__kb || (this.__kb = {});
      this.__kb._onLocaleChange = _.bind(this._onLocaleChange, this);
      this.__kb._onChange = options.onChange;
      if (this.value_holder) {
        value = ko.utils.unwrapObservable(this.value_holder);
      }
      kb.utils.wrappedByKey(this, 'vo', ko.observable(!value ? null : this.read(value, null)));
      if (this.write && (typeof this.write !== 'function')) {
        throw 'LocalizedObservable: options.write is not a function for read_write model attribute';
      }
      observable = kb.utils.wrappedObservable(this, ko.dependentObservable({
        read: _.bind(this._onGetValue, this),
        write: this.write ? _.bind(this._onSetValue, this) : (function() {
          throw 'kb.LocalizedObservable: value is read only';
        }),
        owner: this.view_model
      }));
      observable.destroy = _.bind(this.destroy, this);
      observable.observedValue = _.bind(this.observedValue, this);
      observable.resetToCurrent = _.bind(this.resetToCurrent, this);
      kb.locale_manager.bind('change', this.__kb._onLocaleChange);
      if (options.hasOwnProperty('default')) {
        observable = ko.defaultWrapper(observable, options["default"]);
      }
      return observable;
    }

    LocalizedObservable.prototype.destroy = function() {
      kb.locale_manager.unbind('change', this.__kb._onLocaleChange);
      this.view_model = null;
      return kb.utils.wrappedDestroy(this);
    };

    LocalizedObservable.prototype.resetToCurrent = function() {
      var current_value, observable, value_observable;
      value_observable = kb.utils.wrappedByKey(this, 'vo');
      value_observable(null);
      observable = kb.utils.wrappedObservable(this);
      current_value = this.value_holder && observable ? this.read(ko.utils.unwrapObservable(this.value_holder)) : null;
      return this._onSetValue(current_value);
    };

    LocalizedObservable.prototype.observedValue = function(value) {
      if (arguments.length === 0) {
        return this.value_holder;
      }
      this.value_holder = value;
      this._onLocaleChange();
      return this;
    };

    LocalizedObservable.prototype._onGetValue = function() {
      var value_observable;
      if (this.value_holder) {
        ko.utils.unwrapObservable(this.value_holder);
      }
      value_observable = kb.utils.wrappedByKey(this, 'vo');
      value_observable();
      return this.read(ko.utils.unwrapObservable(this.value_holder));
    };

    LocalizedObservable.prototype._onSetValue = function(value) {
      var value_observable;
      this.write(value, ko.utils.unwrapObservable(this.value_holder));
      value_observable = kb.utils.wrappedByKey(this, 'vo');
      value_observable(value);
      if (this.__kb._onChange) {
        return this.__kb._onChange(value);
      }
    };

    LocalizedObservable.prototype._onLocaleChange = function() {
      var value, value_observable;
      value = this.read(ko.utils.unwrapObservable(this.value_holder));
      value_observable = kb.utils.wrappedByKey(this, 'vo');
      value_observable(value);
      if (this.__kb._onChange) {
        return this.__kb._onChange.onChange(value);
      }
    };

    return LocalizedObservable;

  })();

  kb.localizedObservable = function(value, options, view_model) {
    return new kb.LocalizedObservable(value, options, view_model);
  };

  /*
    knockback_observable.js
    (c) 2011, 2012 Kevin Malakoff.
    Knockback.Observable is freely distributable under the MIT license.
    See the following for full license details:
      https://github.com/kmalakoff/knockback/blob/master/LICENSE
  */


  kb.Observable = (function() {

    function Observable(model, mapping_info, view_model) {
      var model_ref, observable, value_observable;
      this.view_model = view_model != null ? view_model : {};
      if (!model) {
        throw 'Observable: model is missing';
      }
      if (!mapping_info) {
        throw 'Observable: mapping_info is missing';
      }
      this.__kb || (this.__kb = {});
      this.__kb._onModelChange = _.bind(this._onModelChange, this);
      this.__kb._onModelLoaded = _.bind(this._onModelLoaded, this);
      this.__kb._onModelUnloaded = _.bind(this._onModelUnloaded, this);
      this.key = _.isString(mapping_info) || ko.isObservable(mapping_info) ? mapping_info : mapping_info.key;
      if (!this.key) {
        throw 'Observable: key is missing';
      }
      this.args = mapping_info.args;
      this.read = mapping_info.read;
      this.write = mapping_info.write;
      value_observable = kb.utils.wrappedByKey(this, 'vo', ko.observable());
      observable = kb.utils.wrappedObservable(this, ko.dependentObservable({
        read: _.bind(this._onGetValue, this),
        write: _.bind(this._onSetValue, this),
        owner: this.view_model
      }));
      if (Backbone.ModelRef && (model instanceof Backbone.ModelRef)) {
        kb.utils.wrappedModelRef(observable, model, {
          loaded: this.__kb._onModelLoaded,
          unloaded: this.__kb._onModelUnloaded
        });
        model_ref = model;
        model = model_ref.model();
      } else {
        kb.utils.wrappedObject(observable, model);
      }
      observable.destroy = _.bind(this.destroy, this);
      if (!model_ref || model_ref.isLoaded()) {
        model.bind('change', this.__kb._onModelChange);
        value_observable.notifySubscribers(value_observable());
      }
      if (mapping_info.localizer) {
        observable = new mapping_info.localizer(observable);
      }
      if (mapping_info.hasOwnProperty('default')) {
        observable = kb.defaultWrapper(observable, mapping_info["default"]);
      }
      return observable;
    }

    Observable.prototype.destroy = function() {
      this._modelUnbind(kb.utils.wrappedObject(kb.utils.wrappedObservable(this)));
      this.key = null;
      this.args = null;
      this.read = null;
      this.write = null;
      this.view_model = null;
      return kb.utils.wrappedDestroy(this);
    };

    Observable.prototype._onGetValue = function() {
      var arg, args, model, observable, value_observable, _i, _len, _ref;
      value_observable = kb.utils.wrappedByKey(this, 'vo');
      value_observable();
      args = [ko.utils.unwrapObservable(this.key)];
      observable = kb.utils.wrappedObservable(this);
      if (!observable) {
        return null;
      }
      model = kb.utils.wrappedObject(observable);
      if (!model) {
        return null;
      }
      if (!_.isUndefined(this.args)) {
        if (_.isArray(this.args)) {
          _ref = this.args;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            arg = _ref[_i];
            args.push(ko.utils.unwrapObservable(arg));
          }
        } else {
          args.push(ko.utils.unwrapObservable(this.args));
        }
      }
      if (this.read) {
        return this.read.apply(this.view_model, args);
      } else {
        return model.get.apply(model, args);
      }
    };

    Observable.prototype._onSetValue = function(value) {
      var arg, args, model, set_info, value_observable, _i, _len, _ref;
      model = kb.utils.wrappedObject(kb.utils.wrappedObservable(this));
      if (model) {
        set_info = {};
        set_info[ko.utils.unwrapObservable(this.key)] = value;
        args = this.write ? [value] : [set_info];
        if (!_.isUndefined(this.args)) {
          if (_.isArray(this.args)) {
            _ref = this.args;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              arg = _ref[_i];
              args.push(ko.utils.unwrapObservable(arg));
            }
          } else {
            args.push(ko.utils.unwrapObservable(this.args));
          }
        }
        if (this.write) {
          this.write.apply(this.view_model, args);
        } else {
          model.set.apply(model, args);
        }
      }
      value_observable = kb.utils.wrappedByKey(this, 'vo');
      return value_observable(value);
    };

    Observable.prototype._modelBind = function(model) {
      if (!model) {
        return;
      }
      model.bind('change', this.__kb._onModelChange);
      if (Backbone.RelationalModel && (model instanceof Backbone.RelationalModel)) {
        model.bind('add', this.__kb._onModelChange);
        model.bind('remove', this.__kb._onModelChange);
        return model.bind('update', this.__kb._onModelChange);
      }
    };

    Observable.prototype._modelUnbind = function(model) {
      if (!model) {
        return;
      }
      model.unbind('change', this.__kb._onModelChange);
      if (Backbone.RelationalModel && (model instanceof Backbone.RelationalModel)) {
        model.unbind('add', this.__kb._onModelChange);
        model.unbind('remove', this.__kb._onModelChange);
        return model.unbind('update', this.__kb._onModelChange);
      }
    };

    Observable.prototype._onModelLoaded = function(model) {
      var value_observable;
      kb.utils.wrappedObject(kb.utils.wrappedObservable(this), model);
      this._modelBind(model);
      value_observable = kb.utils.wrappedByKey(this, 'vo');
      return value_observable(this._onGetValue());
    };

    Observable.prototype._onModelUnloaded = function(model) {
      if (this.__kb.localizer && this.__kb.localizer.destroy) {
        this.__kb.localizer.destroy();
        this.__kb.localizer = null;
      }
      this._modelUnbind(model);
      return kb.utils.wrappedObject(kb.utils.wrappedObservable(this), null);
    };

    Observable.prototype._onModelChange = function() {
      var model, value_observable;
      model = kb.utils.wrappedObject(kb.utils.wrappedObservable(this));
      if ((model && model.hasChanged) && !model.hasChanged(ko.utils.unwrapObservable(this.key))) {
        return;
      }
      value_observable = kb.utils.wrappedByKey(this, 'vo');
      return value_observable(this._onGetValue());
    };

    return Observable;

  })();

  kb.observable = function(model, mapping_info, view_model) {
    return new kb.Observable(model, mapping_info, view_model);
  };

  /*
    knockback_observables.js
    (c) 2011, 2012 Kevin Malakoff.
    Knockback.Observables is freely distributable under the MIT license.
    See the following for full license details:
      https://github.com/kmalakoff/knockback/blob/master/LICENSE
  */


  kb.Observables = (function() {

    function Observables(model, mappings_info, view_model, options) {
      var is_string, key, mapping_info, property_name, _i, _len, _ref, _ref1;
      if (!model) {
        throw 'Observables: model is missing';
      }
      if (!(mappings_info && (_.isObject(mappings_info) || _.isArray(mappings_info)))) {
        throw 'Observables: mappings_info is missing';
      }
      this.__kb || (this.__kb = {});
      if (_.isArray(mappings_info)) {
        this.__kb.mappings_info = {};
        for (_i = 0, _len = mappings_info.length; _i < _len; _i++) {
          key = mappings_info[_i];
          this.__kb.mappings_info[key] = {};
        }
      } else {
        this.__kb.mappings_info = mappings_info;
      }
      this.__kb.view_model = _.isUndefined(view_model) ? this : view_model;
      if (!_.isUndefined(options)) {
        _ref = this.__kb.mappings_info;
        for (property_name in _ref) {
          mapping_info = _ref[property_name];
          is_string = _.isString(mapping_info);
          if (is_string) {
            mapping_info = {
              key: mapping_info
            };
          }
          if (!mapping_info.hasOwnProperty('key')) {
            mapping_info.key = property_name;
          }
          this[property_name] = this.__kb.view_model[property_name] = kb.observable(model, mapping_info, this.__kb.view_model);
        }
      } else {
        _ref1 = this.__kb.mappings_info;
        for (property_name in _ref1) {
          mapping_info = _ref1[property_name];
          if (!mapping_info.hasOwnProperty('key')) {
            mapping_info.key = property_name;
          }
          this[property_name] = this.__kb.view_model[property_name] = kb.observable(model, mapping_info, this.__kb.view_model);
        }
      }
    }

    Observables.prototype.destroy = function() {
      var mapping_info, property_name, _ref;
      _ref = this.__kb.mappings_info;
      for (property_name in _ref) {
        mapping_info = _ref[property_name];
        if (this.__kb.view_model[property_name]) {
          this.__kb.view_model[property_name].destroy();
        }
        this.__kb.view_model[property_name] = null;
        this[property_name] = null;
      }
      return kb.utils.wrappedDestroy(this);
    };

    Observables.prototype.setToDefault = function() {
      var mapping_info, property_name, _ref, _results;
      _ref = this.__kb.mappings_info;
      _results = [];
      for (property_name in _ref) {
        mapping_info = _ref[property_name];
        _results.push(this.__kb.view_model[property_name].setToDefault());
      }
      return _results;
    };

    return Observables;

  })();

  kb.observables = function(model, mappings_info, view_model, options) {
    return new kb.Observables(model, mappings_info, view_model, options);
  };

  /*
    knockback_triggered_observable.js
    (c) 2011, 2012 Kevin Malakoff.
    Knockback.Observable is freely distributable under the MIT license.
    See the following for full license details:
      https://github.com/kmalakoff/knockback/blob/master/LICENSE
  */


  kb.TriggeredObservable = (function() {

    function TriggeredObservable(model, event_name) {
      var model_ref, observable;
      this.event_name = event_name;
      if (!model) {
        throw 'Observable: model is missing';
      }
      if (!this.event_name) {
        throw 'Observable: event_name is missing';
      }
      this.__kb || (this.__kb = {});
      this.__kb._onValueChange = _.bind(this._onValueChange, this);
      this.__kb._onModelLoaded = _.bind(this._onModelLoaded, this);
      this.__kb._onModelUnloaded = _.bind(this._onModelUnloaded, this);
      kb.utils.wrappedByKey(this, 'vo', ko.observable());
      observable = kb.utils.wrappedObservable(this, ko.dependentObservable(_.bind(this._onGetValue, this)));
      if (Backbone.ModelRef && (model instanceof Backbone.ModelRef)) {
        kb.utils.wrappedModelRef(observable, model, {
          loaded: this.__kb._onModelLoaded,
          unloaded: this.__kb._onModelUnloaded
        });
        model_ref = model;
        model = model_ref.model();
      } else {
        kb.utils.wrappedObject(observable, model);
      }
      observable.destroy = _.bind(this.destroy, this);
      if (!model_ref || model_ref.isLoaded()) {
        this._onModelLoaded(model);
      }
      return observable;
    }

    TriggeredObservable.prototype.destroy = function() {
      var model;
      model = kb.utils.wrappedObject(kb.utils.wrappedObservable(this));
      if (model) {
        this._onModelUnloaded(model);
      }
      this.options = null;
      this.view_model = null;
      return kb.utils.wrappedDestroy(this);
    };

    TriggeredObservable.prototype._onGetValue = function() {
      return kb.utils.wrappedByKey(this, 'vo')();
    };

    TriggeredObservable.prototype._onModelLoaded = function(model) {
      kb.utils.wrappedObject(kb.utils.wrappedObservable(this), model);
      model.bind(this.event_name, this.__kb._onValueChange);
      return this._onValueChange();
    };

    TriggeredObservable.prototype._onModelUnloaded = function(model) {
      var observable;
      observable = kb.utils.wrappedObservable(this);
      model.unbind(this.event_name, this.__kb._onValueChange);
      return kb.utils.wrappedObject(observable, null);
    };

    TriggeredObservable.prototype._onValueChange = function() {
      var current_value, model, observable, value_observable;
      observable = kb.utils.wrappedObservable(this);
      value_observable = kb.utils.wrappedByKey(this, 'vo');
      current_value = value_observable();
      model = kb.utils.wrappedObject(observable);
      if (current_value !== model) {
        return value_observable(model);
      } else {
        return value_observable.valueHasMutated();
      }
    };

    return TriggeredObservable;

  })();

  kb.triggeredObservable = function(model, event_name) {
    return new kb.TriggeredObservable(model, event_name);
  };

  /*
    knockback_attribute_observable.js
    (c) 2012 Kevin Malakoff.
    Knockback.AttributeObservable is freely distributable under the MIT license.
    See the following for full license details:
      https://github.com/kmalakoff/knockback/blob/master/LICENSE
  */


  kb.AttributeObservable = (function() {

    function AttributeObservable(model, key, options) {
      var observable;
      if (options == null) {
        options = {};
      }
      kb.utils.wrappedByKey(this, 'vo', ko.observable());
      observable = kb.utils.wrappedObservable(this, ko.dependentObservable({
        read: _.bind(this.read, this),
        write: _.bind(this.write, this)
      }));
      kb.utils.wrappedObject(observable, model);
      kb.utils.wrappedStore(observable, options.store);
      kb.utils.wrappedFactory(observable, options.factory);
      kb.utils.wrappedPath(observable, kb.utils.pathJoin(options.path, key));
      this.key = key;
      observable.valueType = _.bind(this.valueType, this);
      observable.destroy = _.bind(this.destroy, this);
      observable.model = _.bind(this.model, this);
      observable.update = _.bind(this.update, this);
      this.update();
      return observable;
    }

    AttributeObservable.prototype.destroy = function() {
      return kb.utils.wrappedDestroy(this);
    };

    AttributeObservable.prototype.read = function() {
      return ko.utils.unwrapObservable(kb.utils.wrappedByKey(this, 'vo'));
    };

    AttributeObservable.prototype.write = function(new_value) {
      var model, observable, set_info;
      observable = kb.utils.wrappedObservable(this);
      model = kb.utils.wrappedObject(observable);
      if (model && model.get(this.key) !== new_value) {
        set_info = {};
        set_info[this.key] = new_value;
        model.set(set_info);
      }
      return this.update(new_value);
    };

    AttributeObservable.prototype.model = function(new_model) {
      var model, observable;
      observable = kb.utils.wrappedObservable(this);
      model = kb.utils.wrappedObject(observable);
      if (arguments.length === 0) {
        return model;
      }
      if (model === new_model) {
        return;
      }
      kb.utils.wrappedObject(observable, new_model);
      return this.update();
    };

    AttributeObservable.prototype.update = function(new_value) {
      var model, observable, type, value_observable;
      observable = kb.utils.wrappedObservable(this);
      model = kb.utils.wrappedObject(observable);
      if (model && !arguments.length) {
        new_value = model.get(this.key);
      }
      value_observable = kb.utils.wrappedByKey(this, 'vo');
      if (!value_observable) {
        this._createValueObservable(new_value);
        return;
      }
      type = this.valueType();
      if (type === kb.TYPE_MODEL) {
        if (new_value && !new_value instanceof Backbone.Model) {
          return this._createValueObservable(new_value);
        } else {
          if (value_observable.model() !== new_value) {
            return value_observable.model(new_value);
          }
        }
      } else if (type === kb.TYPE_COLLECTION) {
        if (new_value && !new_value instanceof Backbone.Collection) {
          return this._createValueObservable(new_value);
        } else {
          if (value_observable.collection() !== new_value) {
            return value_observable.collection(new_value);
          }
        }
      } else {
        if (new_value && (new_value instanceof Backbone.Model || new_value instanceof Backbone.Collection)) {
          return this._createValueObservable(new_value);
        } else {
          if (value_observable() !== new_value) {
            return value_observable(new_value);
          }
        }
      }
    };

    AttributeObservable.prototype.valueType = function() {
      var value_observable;
      value_observable = kb.utils.wrappedByKey(this, 'vo');
      if (!value_observable) {
        value_observable = this._createValueObservable(new_value);
      }
      if (!ko.isObservable(value_observable)) {
        return kb.TYPE_MODEL;
      }
      if (kb.utils.observableInstanceOf(value_observable, kb.CollectionObservable)) {
        return kb.TYPE_COLLECTION;
      }
      return kb.TYPE_SIMPLE;
    };

    AttributeObservable.prototype._createValueObservable = function(new_value) {
      var observable, previous_value_observable, store, value_observable;
      observable = kb.utils.wrappedObservable(this);
      store = kb.utils.wrappedStore(observable);
      previous_value_observable = kb.utils.wrappedByKey(this, 'vo');
      value_observable = kb.utils.wrappedByKey(this, 'vo', store.findOrCreateObservable(new_value, kb.utils.wrappedPath(observable), kb.utils.wrappedFactory(observable)));
      previous_value_observable.notifySubscribers(ko.utils.unwrapObservable(value_observable));
      store.releaseObservable(previous_value_observable);
      return value_observable;
    };

    return AttributeObservable;

  })();

  kb.attributeObservable = function(model, key, options) {
    return new kb.AttributeObservable(model, key, options);
  };

  /*
    knockback_view_model.js
    (c) 2011, 2012 Kevin Malakoff.
    Knockback.Observable is freely distributable under the MIT license.
    See the following for full license details:
      https://github.com/kmalakoff/knockback/blob/master/LICENSE
  */


  kb.ViewModel = (function(_super) {

    __extends(ViewModel, _super);

    function ViewModel(model, options) {
      var factory, key, missing, model_ref, _i, _len;
      if (options == null) {
        options = {};
      }
      ViewModel.__super__.constructor.apply(this, arguments);
      if (kb.statistics) {
        kb.statistics.register('kb.ViewModel', this);
      }
      kb.Store.registerOrCreateStoreFromOptions(model, this, options);
      factory = kb.utils.wrappedFactory(this, new kb.Factory(options.factory));
      kb.utils.wrappedPath(this, options.path);
      if (options.mappings) {
        factory.addPathMappings(options.mappings);
      }
      this.__kb._onModelChange = _.bind(this._onModelChange, this);
      this.__kb._onModelLoaded = _.bind(this._onModelLoaded, this);
      this.__kb._onModelUnloaded = _.bind(this._onModelUnloaded, this);
      this.__kb.internals = options.internals;
      this.__kb.requires = options.requires;
      if (Backbone.ModelRef && (model instanceof Backbone.ModelRef)) {
        kb.utils.wrappedModelRef(this, model, {
          loaded: this.__kb._onModelLoaded,
          unloaded: this.__kb._onModelUnloaded
        });
        model_ref = model;
        model = model_ref.model();
      } else {
        kb.utils.wrappedObject(this, model);
      }
      if (model) {
        this._onModelLoaded(model);
      }
      if (!this.__kb.internals && !this.__kb.requires) {
        return this;
      }
      missing = _.union((this.__kb.internals ? this.__kb.internals : []), (this.__kb.requires ? this.__kb.requires : []));
      if (!model_ref || model_ref.isLoaded()) {
        missing = _.difference(missing, _.keys(model.attributes));
      }
      for (_i = 0, _len = missing.length; _i < _len; _i++) {
        key = missing[_i];
        this._updateAttributeObservable(model, key);
      }
    }

    ViewModel.prototype.__destroy = function() {
      this._modelUnbind(kb.utils.wrappedObject(this));
      kb.utils.release(this, true);
      kb.utils.wrappedDestroy(this);
      ViewModel.__super__.__destroy.apply(this, arguments);
      if (kb.statistics) {
        return kb.statistics.unregister('kb.ViewModel', this);
      }
    };

    ViewModel.prototype.model = function(new_model) {
      var model;
      model = kb.utils.wrappedObject(this);
      if (arguments.length === 0) {
        return model;
      }
      if (new_model === model) {
        return;
      }
      if (model) {
        this._onModelUnloaded(model);
      }
      if (new_model) {
        return this._onModelLoaded(new_model);
      }
    };

    ViewModel.prototype._modelBind = function(model) {
      if (!model) {
        return;
      }
      model.bind('change', this.__kb._onModelChange);
      if (Backbone.RelationalModel && (model instanceof Backbone.RelationalModel)) {
        model.bind('add', this.__kb._onModelChange);
        model.bind('remove', this.__kb._onModelChange);
        return model.bind('update', this.__kb._onModelChange);
      }
    };

    ViewModel.prototype._modelUnbind = function(model) {
      if (!model) {
        return;
      }
      model.unbind('change', this.__kb._onModelChange);
      if (Backbone.RelationalModel && (model instanceof Backbone.RelationalModel)) {
        model.unbind('add', this.__kb._onModelChange);
        model.unbind('remove', this.__kb._onModelChange);
        return model.unbind('update', this.__kb._onModelChange);
      }
    };

    ViewModel.prototype._onModelLoaded = function(model) {
      var key, _results;
      kb.utils.wrappedObject(this, model);
      this._modelBind(model);
      _results = [];
      for (key in model.attributes) {
        _results.push(this._updateAttributeObservable(model, key));
      }
      return _results;
    };

    ViewModel.prototype._onModelUnloaded = function(model) {
      var key, _results;
      this._modelUnbind(model);
      kb.utils.wrappedObject(this, null);
      _results = [];
      for (key in model.attributes) {
        _results.push(this._updateAttributeObservable(null, key));
      }
      return _results;
    };

    ViewModel.prototype._onModelChange = function() {
      var key, model, _results, _results1;
      model = kb.utils.wrappedObject(this);
      if (model._changed) {
        _results = [];
        for (key in model.attributes) {
          _results.push(model.hasChanged(key) ? this._updateAttributeObservable(model, key) : void 0);
        }
        return _results;
      } else if (model.changed) {
        _results1 = [];
        for (key in model.changed) {
          _results1.push(this._updateAttributeObservable(model, key));
        }
        return _results1;
      }
    };

    ViewModel.prototype._updateAttributeObservable = function(model, key) {
      var observable, vm_key;
      vm_key = this.__kb.internals && _.contains(this.__kb.internals, key) ? '_' + key : key;
      observable = this[vm_key];
      if (observable) {
        if (!kb.utils.observableInstanceOf(observable, kb.AttributeObservable)) {
          return;
        }
        if (observable.model() !== model) {
          return observable.model(model);
        } else {
          return observable.update();
        }
      } else {
        return this[vm_key] = kb.attributeObservable(model, key, {
          store: kb.utils.wrappedStore(this),
          factory: kb.utils.wrappedFactory(this),
          path: kb.utils.wrappedPath(this)
        });
      }
    };

    return ViewModel;

  })(kb.RefCountable);

  kb.viewModel = function(model, options) {
    return new kb.ViewModel(model, options);
  };

}).call(this);
