// Generated by CoffeeScript 1.6.3
(function() {
  var kb, ko, _;

  module("knockback_core utils");

  ko = !window.ko && (typeof require !== 'undefined') ? require('knockout') : window.ko;

  kb = !window.kb && (typeof require !== 'undefined') ? require('knockback') : window.kb;

  _ = kb._;

  test("TEST DEPENDENCY MISSING", function() {
    ok(!!ko, 'ko');
    ok(!!_, '_');
    ok(!!kb.Model, 'kb.Model');
    ok(!!kb.Collection, 'kb.Collection');
    return ok(!!kb, 'kb');
  });

  test("kb.renderTemplate", function() {
    var ViewModel, el, view_model, was_called;
    kb.statistics = new kb.Statistics();
    if (!ko.version) {
      return ok(true);
    }
    ViewModel = (function() {
      function ViewModel() {
        this.name = ko.observable('Bob');
      }

      ViewModel.prototype.afterRender = function() {
        return this.was_called = true;
      };

      return ViewModel;

    })();
    view_model = new ViewModel();
    ok(!view_model.was_called, 'afterRender not called yet');
    el = $('<script type="text/x-jquery-tmpl" id="the_template1"><div data-bind="text: name"></div></script>');
    $('body').append(el);
    kb.renderTemplate('the_template1', view_model);
    ok(view_model.was_called, 'afterRender was called');
    was_called = false;
    view_model = new ViewModel();
    ok(!view_model.was_called, 'afterRender (options) not called yet');
    ok(!view_model.was_called, 'afterRender not called yet');
    el = $('<script type="text/x-jquery-tmpl" id="the_template2"><div data-bind="text: name"></div></script>');
    $('body').append(el);
    kb.renderTemplate('the_template2', view_model, {
      afterRender: function() {
        return was_called = true;
      }
    });
    ok(was_called, 'afterRender (options) was called');
    ok(!view_model.was_called, 'afterRender was not called');
    equal(kb.statistics.registeredStatsString('all released'), 'all released', "Cleanup: stats");
    return kb.statistics = null;
  });

}).call(this);
