// Generated by CoffeeScript 1.3.3
var ViewModel, model, view_model;

model = new Backbone.Model({
  number: 33
});

ViewModel = function(model) {
  this.number = kb.observable(model, {
    key: 'number',
    read_only: true
  });
  this.number_wrapper = ko.computed({
    read: this.number,
    write: function(value) {
      try {
        return this.number(value);
      } catch (e) {
        return alert("" + e + ". Model value: " + (model.get('number')));
      }
    },
    owner: this
  });
  return this;
};

view_model = new ViewModel(model);

ko.applyBindings(view_model, $('#kboo_read_only')[0]);
