// Generated by CoffeeScript 1.3.3

/*
  knockback_statistics.js
  (c) 2012 Kevin Malakoff.
  Knockback.Stats is freely distributable under the MIT license.
  See the following for full license details:
    https://github.com/kmalakoff/knockback/blob/master/LICENSE
*/


(function() {
  var kb, _;

  if (typeof require !== 'undefined') {
    _ = require('underscore');
  } else {
    _ = window._;
  }

  if (_ && (_.hasOwnProperty('_'))) {
    _ = _._;
  }

  kb = !window.kb && (typeof require !== 'undefined') ? require('knockback') : window.kb;

  kb.Statistics = (function() {

    function Statistics() {
      this.type_trackers = {};
    }

    Statistics.prototype.typeTracker = function(type) {
      var type_tracker;
      if (this.type_trackers.hasOwnProperty(type)) {
        return this.type_trackers[type];
      }
      type_tracker = [];
      this.type_trackers[type] = type_tracker;
      return type_tracker;
    };

    Statistics.prototype.register = function(type, obj) {
      return this.typeTracker(type).push(obj);
    };

    Statistics.prototype.unregister = function(type, obj) {
      var index, type_tracker;
      type_tracker = this.typeTracker(type);
      index = _.indexOf(type_tracker, obj);
      if (index < 0) {
        throw "failed to unregister type: " + type;
      }
      return type_tracker.splice(index, 1);
    };

    Statistics.prototype.registeredCount = function(type) {
      return this.typeTracker(type).length;
    };

    return Statistics;

  })();

}).call(this);
