// Generated by CoffeeScript 1.3.3

ko.bindingHandlers['classes'] = {
  update: function(element, value_accessor) {
    var key, state, _ref;
    _ref = ko.utils.unwrapObservable(value_accessor());
    for (key in _ref) {
      state = _ref[key];
      if (state) {
        $(element).addClass(key);
      } else {
        $(element).removeClass(key);
      }
    }
    return this;
  }
};

window.loadUrl = function(url) {
  return Backbone.history.loadUrl(url);
};

window.loadUrlFn = function(url) {
  return function() {
    return Backbone.history.loadUrl(url);
  };
};
