// Generated by CoffeeScript 1.3.1
var model, view_model;

model = new Backbone.Model({
  date: new Date()
});

view_model = {
  date: kb.observable(model, {
    key: 'date',
    localizer: LongDateLocalizer
  }),
  toggleLocale: function() {
    if (kb.locale_manager.getLocale() === 'en-GB') {
      return kb.locale_manager.setLocale('fr-FR');
    } else {
      return kb.locale_manager.setLocale('en-GB');
    }
  }
};

ko.applyBindings(view_model, $('#kblo_read_write')[0]);
