// Generated by CoffeeScript 1.3.3
var LocalizedStringLocalizer;

LocalizedStringLocalizer = kb.LocalizedObservable.extend({
  constructor: function(value, options, view_model) {
    kb.LocalizedObservable.prototype.constructor.apply(this, arguments);
    return kb.utils.wrappedObservable(this);
  },
  read: function(string_id) {
    if (string_id) {
      return kb.locale_manager.get(string_id);
    } else {
      return '';
    }
  }
});
