// Generated by CoffeeScript 1.3.3
var texts, view_model;

texts = new Backbone.Model({
  main_text_id: 'body'
});

view_model = {
  main_text: kb.observable(texts, {
    key: 'main_text_id',
    localizer: LocalizedStringLocalizer
  }),
  toggleLocale: function() {
    if (kb.locale_manager.getLocale() === 'en-GB') {
      return kb.locale_manager.setLocale('fr-FR');
    } else {
      return kb.locale_manager.setLocale('en-GB');
    }
  }
};

ko.applyBindings(view_model, $('#kblo_read_only')[0]);
