name: CI
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Node.js ${{ matrix.node-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["latest"]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: git config --global user.name "Github Actions"
      - run: git config --global user.email "actions@users.noreply.github.com"
      - run: npm install node-version-use -g
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test:engines
